version: '3.8'

services:
  app:
    build: .
    network_mode: host
    environment:
      - ENV=production
      - DEBUG=false
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env.production
